server:
    port: 8087

spring:
    application:
      name: RATING-SERVICE
    datasource:
        url: jdbc:postgresql://localhost:5432/ratingservice
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
      import: configserver:http://localhost:8085    
   

